  name: Generate Cypress Report
  on:
    push:
      branches:
        - 'main'
  
  jobs:
    cypress-test:
      name: Run on Chrome 83
      runs-on: ubuntu-latest
      container: cypress/browsers:node12.18.0-chrome83-ff77
      steps:
        - uses: actions/checkout@v3
        - name: Download Cypress
        - uses: bahmutov/npm-install@v1
        - uses: cypress-io/github-action@v6
          with:
                  install-command: npm i --force
          env:
                  CYPRESS_INSTALL_BINARY: 0
                  
        - name: Install Cypress
          run: npx cypress install
  
        - name: Run Cypress tests
          run: npm run test:allure
          continue-on-error: true
  
        - name: Copy test execution videos, screenshots and reports
          run: |
            mkdir public
            cp -r cypress/videos public/videos
            cp -r cypress/screenshots public/screenshots
            cp -a allure-report/. public
            cp -r allure-results public/allure-results
        
        - name: Deploy report page to GitHub Page
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
